[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nlxdftools"
version = "0.0.1"
authors = [
    {name="Jamie Forth", email="j.forth@gold.ac.uk"},
]
description = "Tools for working with NEUROLIVE XDF data files."
readme = "README.md"
requires-python = ">=3.11"
license = {text = "AGPL-3.0-or-later"}

dependencies = [
    "pandas[performance]",
    "pyxdftools @ git+https://github.com/jamieforth/pyxdf-tools.git@main",
    "scipy",
    "matplotlib>=3.9.2",
]
